### ISSUE TITLE
qiita-stocker-backendをDocker上で動作させる

### ISSUE THREAD

**Issue by keitakn** [nekochans/redux-next-boilerplate#38]
# Doneの定義
- [docker-compose-boilerplate](https://github.com/nekochans/docker-compose-boilerplate) のREADMEを参考に環境構築が出来ている事
- コンテナ内で qiita-stocker-backend のテストを実行し正常終了する事が確認出来ている事
- コンテナ内の qiita-stocker-backend にHTTPで通信出来る事が確認出来ている事

**Comment by keitakn** [comment]
@kobayashi-m42 ストーリーポイント、個人的には3かなと思う🐱！

ただこれは https://github.com/nekochans/docker-compose-boilerplate のREADMEにある事前準備がどれだけ終わっているかによって変わってくるかも、事前準備がだいたい終わっているなら `2` だけど終わってないなら `3` は必要かも！

**Comment by kobayashi-m42** [comment]
@keitakn 
事前準備が終わってるから、`2`にするね！

**Comment by kobayashi-m42** [comment]
Doneの定義を満たしたので、クローズ。
